CSW_URL = "https://nationaalgeoregister.nl/geonetwork/srv/dut/csw"
LOG_LEVEL = "INFO"
WFS_PROTOCOL = "OGC:WFS"
WMS_PROTOCOL = "OGC:WMS"
WCS_PROTOCOL = "OGC:WCS"
WMTS_PROTOCOL = "OGC:WMTS"
PROTOCOLS = [WFS_PROTOCOL, WMS_PROTOCOL, WCS_PROTOCOL, WMTS_PROTOCOL]
