CSW_URL = "https://nationaalgeoregister.nl/geonetwork/srv/dut/csw"
LOG_LEVEL = "ERROR"
WFS_PROTOCOL = "OGC:WFS"
WMS_PROTOCOL = "OGC:WMS"
WCS_PROTOCOL = "OGC:WCS"
WMTS_PROTOCOL = "OGC:WMTS"
ATOM_PROTOCOL = "INSPIRE Atom"
PROTOCOLS = [WFS_PROTOCOL, WMS_PROTOCOL, WCS_PROTOCOL, WMTS_PROTOCOL, ATOM_PROTOCOL]
